### ISSUE TITLE
$. in Csv.foreach doesn't provide accurate file line number 

### ISSUE THREAD

**Issue by ryanmcgary** [csv11/csvreader#3]
$. value isn't accurate

<img width="444" alt="screen shot 2018-10-11 at 8 33 55 pm" src="https://user-images.githubusercontent.com/357870/46842769-2175f580-cd95-11e8-8326-188b6ddce5db.png">

**Comment by ryanmcgary** [comment]
Looking at source I realized Csv.foreach loads entire CSV into memory instead reading one line at a time like stlib CSV. This makes the library unusable for parsing large files.

**Comment by geraldb** [comment]
@ryanmcgary  Csv.foreach reads one char at a time (with getch) - see <https://github.com/csv11/csvreader/blob/master/lib/csvreader/buffer.rb#L18>.   And yes, there's no line / record counter for now (might get added if there's a need).  Cheers. Prost. PS: Note, for discussions if you care - the forum is for questions and comments, see <https://groups.google.com/group/wwwmake>.
